In [42]:
import os
import numpy as np


### Initialize Grid Data

In [104]:
def check_for_location(x,y,n):
    global grid
    # check row-wise, 
    for col in range(9):
        if grid[x][col] == n:
            return False
    
    # check col-wise
    for row in range(9):
        if grid[row][y] == n:
            return False
    
    # check in box:
    for row in range((x//3)*3,(x//3)*3+3):
        for col in range((y//3)*3,(y//3)*3+3):
            if grid[row][col] ==n:
                return False
    return True
    

x=1
y=2
for n in range(1,10):
    if check_for_location(x,y,n):
        print("({},{})={}".format(x,y,n))
        grid[x][y]=n
        print(grid)
    

In [117]:
def solve():
    global grid
    # print("There are {} zeros in grid".format(grid.size - np.count_nonzero(grid)))
    for x in range(9):
        for y in range(9):
            if grid[x][y]==0:
                for n in range(1,10):
                    if check_for_location(x,y,n):
                        grid[x][y]=n
                        # print(grid)
                        #input("Continue?")
                        solve()
                        grid[x][y]=0
                return
    print("Output Grid Solution:")
    print(grid)
    input("More?")

In [115]:
grid=np.zeros((9,9),dtype=int)
grid[0][3]=2
grid[0][4]=6
grid[0][6]=7
grid[0][8]=1
grid[1][0]=6
grid[1][1]=8
grid[1][4]=7
grid[1][7]=9
grid[2][0]=1
grid[2][1]=9
grid[2][5]=4
grid[2][6]=5
grid[3][0]=8
grid[3][1]=2
grid[3][3]=1
grid[3][7]=4
grid[4][2]=4
grid[4][3]=6
grid[4][5]=2
#grid[4][6]=9
#grid[5][1]=5
grid[5][5]=3
grid[5][7]=2
grid[5][8]=8
grid[6][2]=9
grid[6][3]=3
grid[6][7]=7
grid[6][8]=4
grid[7][1]=4
grid[7][4]=5
grid[7][7]=3
grid[7][8]=6
grid[8][0]=7
grid[8][2]=3
grid[8][4]=1
grid[8][5]=8

print("Input Grid")
print(grid)
solve()

Input Grid
[[0 0 0 2 6 0 7 0 1]
 [6 8 0 0 7 0 0 9 0]
 [1 9 0 0 0 4 5 0 0]
 [8 2 0 1 0 0 0 4 0]
 [0 0 4 6 0 2 0 0 0]
 [0 0 0 0 0 3 0 2 8]
 [0 0 9 3 0 0 0 7 4]
 [0 4 0 0 5 0 0 3 6]
 [7 0 3 0 1 8 0 0 0]]
Output Grid Solution:
[[4 3 5 2 6 9 7 8 1]
 [6 8 2 5 7 1 4 9 3]
 [1 9 7 8 3 4 5 6 2]
 [8 2 6 1 9 5 3 4 7]
 [3 7 4 6 8 2 9 1 5]
 [9 5 1 7 4 3 6 2 8]
 [5 1 9 3 2 6 8 7 4]
 [2 4 8 9 5 7 1 3 6]
 [7 6 3 4 1 8 2 5 9]]
More?


In [107]:
print(grid)

[[0 0 0 2 6 0 7 0 1]
 [6 8 0 0 7 0 0 9 0]
 [1 9 0 0 0 4 5 0 0]
 [8 2 0 1 0 0 0 4 0]
 [0 0 4 6 0 2 9 0 0]
 [0 5 0 0 0 3 0 2 8]
 [0 0 9 3 0 0 0 7 4]
 [0 4 0 0 5 0 0 3 6]
 [7 0 3 0 1 8 0 0 0]]


In [81]:
np.count_nonzero(grid)

36

In [84]:
grid.size

81

In [116]:
grid=np.zeros((9,9),dtype=int)

print("Input Grid")
print(grid)
solve()

Input Grid
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]
Output Grid Solution:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 4 2 9 7 8 5 3 1]
 [9 7 8 5 3 1 6 4 2]]
More?
Output Grid Solution:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 4 8 9 7 1 5 3 2]
 [9 7 2 5 3 8 6 4 1]]
More?
Output Grid Solution:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 7 2 9 3 8 5 4 1]
 [9 4 8 5 7 1 6 3 2]]
More?
Output Grid Solution:
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 

KeyboardInterrupt: 